// console.log(process.arch)
// console.log(process.platform)
// console.log(process.argv)
// console.log(process.version)
//模块版本
// console.log(process.versions)
// console.log(process.execPath)
// console.log(process.execArgv)
// console.log(process.config)
// console.log(process.cwd())
// console.log(process.env)
// console.log(process.pid)
// console.log(process.title)
// console.log(process.memoryUsage())
//nodejs已经运行的秒数
console.log(process.uptime())